config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'articles/show'
  get 'articles/new'
  get 'articles/create'
  get 'articles/edit'
  get 'articles/update'
  get 'articles/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :is_read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<div class="container">
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :is_read, as: :boolean unless @article.new_record?  %>
    <%= f.submit %>
  <% end %>
  <div class="my-3">
    <%= link_to "<i class='fas fa-undo pr-2'></i> Back to index".html_safe, articles_path %>
  </div>
</div>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<div class="container">
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :is_read, as: :boolean unless @article.new_record?  %>
    <%= f.submit %>
  <% end %>
  <div class="my-3">
    <%= link_to "<i class='fas fa-undo pr-2'></i> Back to index".html_safe, articles_path %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h1>Articles show</h1>
  <div class="container w-75">
    <h3 class="d-flex justify-content-between">
      <div class="btn border rounded">
        <%= link_to "<i class='fas fa-dumpster-fire'></i>".html_safe,
        article_path(@article),
        method: :delete,
        data: { confirm: "Are you sure you want to delete #{@article.title}?" } %>
      </div>
      <div>
        <%= link_to @article.title.capitalize, article_path(@article) %>
      </div>
      <div class="btn border rounded">
        <%= link_to '<i class="fas fa-pen pr-1"></i> Edit'.html_safe, edit_article_path(@article) %>
      </div>
    </h3>
    <div class="w-75 m-auto">
      <%= @article.content%>
    </div>
  </div>
  <div class="my-3">
    <%= link_to "<i class='fas fa-undo pr-2'></i> Back to index".html_safe, articles_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <script src="https://pagecdn.io/lib/ace/1.4.12/ace.js" crossorigin="anonymous" integrity="sha256-Q9hnBpgBFstzZOr+OKFOWZWfcF5nFXO8Qz48Nmndo6U=" ></script>
</html>

app/views/shared/_article_header.html.erb
        <h3 class="d-flex justify-content-between">
          <div class="btn border rounded">
            <%= link_to "<i class='fas fa-dumpster-fire'></i>".html_safe,
            article_path(article),
            method: :delete,
            data: { confirm: "Are you sure you want to delete #{article.title}?" } %>
          </div>
          <div>
            <%= link_to article.title.capitalize, article_path(article) %>
          </div>
          <div class="btn border rounded">
            <%= link_to '<i class="fas fa-pen pr-1"></i> Edit'.html_safe, edit_article_path(article) %>
          </div>
        </h3>